services:
  ms-curso-demo3:
    image: mauron/curso-demo:9
    container_name: ms-curso-demo3
    ports:
      - "9094:8080"
    restart: always
    environment:
      URL: "jdbc:mysql://mysqlcurso.mysql.database.azure.com:3306/test"
      PASSWORD: "litethinking2024*"
      USERNAME: "curso"
      TZ: "America/Bogota"
    networks:
      - micros
 
networks:
  micros:
    external:
      name: micros