spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tu_basedatos?useSSL=false&serverTimezone=UTC
    username: tu_usuario
    password: tu_contraseña
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

app:
    factor: 43000
    mensaje: Hola Mundo de java